import os
import nbformat
from nbformat.v4 import new_notebook, new_markdown_cell

nb = new_notebook()

cells = [
    new_markdown_cell('# 🧠 Walkthrough : Architecture des Explications LLM Détaillées\n\nCe notebook récapitule toutes les modifications apportées pour intégrer les explications IA détaillées (en 4 parties) dans l\'application SalesTeam AI. Il est conçu pour expliquer les concepts métiers et techniques à un débutant.'),
    new_markdown_cell('## 1️⃣ L\'Objectif du Changement\n\n**Avant :**\n* La route `/api/recommend` calculait des scores ML et générait pour chaque produit une explication courte de 1 à 2 phrases.\n* **Problème :** Si on recommandait 12 produits, on faisait 12 appels à l\'API HuggingFace d\'un coup. C\'était lent, et ça épuisait immédiatement les crédits gratuits de l\'API. Dans l\'interface, le texte était trop court pour convaincre un client réticent.\n\n**Maintenant :**\n* `/api/recommend` reste super rapide. Les petites explications sur les cartes utilisent le LLM, mais on peut les désactiver facilement.\n* On a créé une toute nouvelle route `/api/explain-detailed`.\n* **Avantage :** L\'explication détaillée n\'est générée **QUE** lorsque le commercial clique spécifiquement sur un produit. C\'est ce qu\'on appelle une génération _à la demande_ (on-demand). L\'interface a été agrandie en une belle modale redimensionnable avec 4 blocs distincts.'),
    new_markdown_cell('## 2️⃣ Les 3 Piliers de la Nouvelle Architecture\n\n### A. Le Contexte Profond (`src/services/deep_context.py`)\nL\'IA (le LLM) n\'invente rien. Pour qu\'elle justifie une recommandation, on doit lui donner des faits têtus. La fonction `retrieve_deep_context()` va fouiller dans les données réelles :\n* **Historique :** Extrait les 6 dernières commandes exactes du client (depuis `main_table.csv`).\n* **Features ML :** Moyennes, tendances, délais habituels.\n* **Score :** Décompose le score mathématique (confiance, boost de timing).\n* **Classement :** Regarde qui est le produit juste en-dessous pour comparer.\n\n### B. Le Prompt Engineering (`src/services/explanation.py`)\nC\'est l\'art de parler à l\'IA. On injecte toutes les données ci-dessus dans un grand texte (le prompt), suivi de **règles strictes** :\n1. Structurer en 4 parties (`Pourquoi ce produit ?`, `Pourquoi cette quantité ?`, etc.).\n2. **Zéro hallucination :** Interdiction d\'inventer un chiffre qui n\'est pas dans le contexte.\n3. **Zéro jargon :** Interdiction d\'utiliser les mots complexes comme *CV*, *boost*, ou *seuil*.\n\n### C. La Couche API et le Cache (`src/services/recommendation.py`)\nPour ne pas recalculer tout le Machine Learning quand on clique sur une carte, `/api/recommend` sauvegarde son résultat en mémoire (`_last_response_cache`). Quand `/api/explain-detailed` est appelé, il pioche directement dans ce cache.'),
    new_markdown_cell('## 3️⃣ Gestion de l\'API HuggingFace et des Crédits\n\n### Qu\'est-ce que HuggingFace ?\nC\'est la plateforme qui héberge le modèle **Llama-3.3-70B-Instruct**. Pour lui parler, on utilise un jeton secret (`HF_TOKEN` dans le fichier `.env`).\n\n### La limite des tokens\nL\'API gratuite autorise environ 1 000 requêtes par mois. Chaque appel d\'explication détaillée consomme environ 600-800 mots (tokens). Si on appelle l\'API pour 12 cartes en même temps, le quota est détruit en quelques minutes !\n\n### Comment on a protégé le quota\n* **Le Circuit Breaker (`_quota_exhausted`) :** Si HuggingFace renvoie une erreur 402 (Quota Epuisé), l\'application l\'enregistre. Les appels suivants n\'essaient même plus de contacter HuggingFace pour éviter le spam réseau.\n* **Le `skip_llm` :** Lors du calcul massif, on utilise un modèle local (fallback) pour les 12 cartes, gardant le vrai LLM HuggingFace pour l\'explication détaillée (le clic utilisateur).'),
    new_markdown_cell('## 4️⃣ Le Fallback Déterministe\n\nQue se passe-t-il si l\'API HuggingFace est en panne, ou si le quota est épuisé (comme c\'est arrivé tout à l\'heure) ?\n\nPlutôt que d\'afficher une erreur, l\'application bascule sur `_rule_based_detailed_explanation()`. C\'est une fonction classique (du code Python pur, sans IA) qui prend les mêmes données et génère les 4 paragraphes en utilisant des textes à trous (des templates).\n\nC\'est moins poétique que l\'IA, mais c\'est **100% fiable, ultra-rapide et gratuit**. Pendant nos tests, vous avez vu ce fallback en action car le token était épuisé !'),
    new_markdown_cell('## 5️⃣ Analyse Critique : Comment améliorer le LLM ?\n\nVous avez cité cet exemple de réponse générée par l\'IA :\n\n> *"Le produit M2539E1 WHITE a un niveau de priorité de 2,2422. Il est suivi de la CAMERA C100 qui a un niveau de priorité de 2,053. [...] une augmentation de 0,250"* \n\n**Le diagnostic de l\'expert :**\nL\'IA a techniquement obéi (elle n\'a pas dit "score final"), mais elle a recraché des décimales incompréhensibles pour un commercial (`2,2422` ou `0,250`).\n\n**Comment corriger cela dans une prochaine version ?**\nIl faut agir sur le `_build_detailed_prompt()` dans `explanation.py` :\n1. **Arrondir en amont :** Ne jamais envoyer `2.2422` dans le prompt. Avant d\'insérer le chiffre dans le texte pour l\'IA, le backend Python doit l\'arrondir (`round(score, 1)` -> `2.2`).\n2. **Traduire la tendance :** Plutôt que d\'envoyer `0.250` pour la tendance, ne donner que le texte : `"Tendance : en très forte hausse"` (en supprimant la valeur brute chiffrée du prompt).\n3. **Règle absolue renforcée :** Ajouter dans le prompt système : *"Ne cite AUCUN chiffre à virgule complexe. Si tu dois comparer deux produits, dis simplement que l\'un est largement prioritaire par rapport à l\'autre sans citer la valeur exacte."*\n\nC\'est la beauté du Prompt Engineering : en filtrant les données brutes avant de les donner à l\'IA, on contrôle son niveau de vulgarisation métier !')
]

nb.cells.extend(cells)

os.makedirs('notebooks', exist_ok=True)
with open('notebooks/15_architecture_explications_llm.ipynb', 'w', encoding='utf-8') as f:
    nbformat.write(nb, f)
print('Notebook créé avec succès dans notebooks/15_architecture_explications_llm.ipynb')
